<?php

namespace ScrumBundle\Repository;

/**
 * EpicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpicsRepository extends \Doctrine\ORM\EntityRepository
{
}
